import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 🎯 মেটাডাটা এখন ১০০% কাজ করবে!
export const metadata = {
  title: "Life Drop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />

        {/* main কন্টেইনার পেইজটি হোল্ড করবে */}
        <main className="flex-1">{children}</main>

        {/* গ্লোবাল ফুটার */}
        <Footer />

        <Toaster position="top-right" />
      </body>
    </html>
  );
}
