import ContactUs from "@/component/ContactUs";
import FeaturedSection from "@/component/FeaturedSection";
import HeroBanner from "@/component/HeroBanner";
import Image from "next/image";

// আপনার app/page.js ফাইলে এটি রেখে দিন
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <HeroBanner />
      <FeaturedSection />
      <ContactUs />
    </div>
  );
}
